import {
    ArrowRightIcon,
    ArrowTopRightIcon,
    ArrowUpIcon,
    CalendarIcon,
    CaretDownIcon,
    CaretSortIcon,
    ChatBubbleIcon,
    CheckIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronUpIcon,
    CircleIcon,
    Cross1Icon,
    DotsVerticalIcon,
    EnterIcon,
    ExitIcon,
    GearIcon,
    LaptopIcon,
    MagnifyingGlassIcon,
    MoonIcon,
    Pencil1Icon,
    PlusCircledIcon,
    PlusIcon,
    ReloadIcon,
    RocketIcon,
    StarFilledIcon,
    SunIcon,
    TrashIcon,
} from "@radix-ui/react-icons"

export const Icons = {
  calendar: CalendarIcon,
  caretUpDown: CaretSortIcon,
  caretDown: CaretDownIcon,
  chatBubble: ChatBubbleIcon,
  check: CheckIcon,
  chevronDown: ChevronDownIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  chevronUp: ChevronUpIcon,
  circle: CircleIcon,
  cross: Cross1Icon,
  dotsVertical: DotsVerticalIcon,
  edit: Pencil1Icon,
  laptop: LaptopIcon,
  loader: ReloadIcon,
  moon: MoonIcon,
  plus: PlusIcon,
  plusCircled: PlusCircledIcon,
  rightArrow: ArrowRightIcon,
  rocket: RocketIcon,
  search: MagnifyingGlassIcon,
  settings: GearIcon,
  signIn: EnterIcon,
  signOut: ExitIcon,
  sun: SunIcon,
  star: StarFilledIcon,
  topRightArrow: ArrowTopRightIcon,
  trash: TrashIcon,
  upArrow: ArrowUpIcon,
}
